# Site settings
title: '@nikolapejo'
slogan: sharing thoughts space
email: pejoski@gmail.com
description: Nikola Pejoski, full stack web developer, frontend engineer, passionate programmer

baseurl: "" # the subpath of your site, e.g. /blog/

url: "http://nikola.pejoski.com" # the base hostname & protocol for your site

social:
  twitter:
    url: https://twitter.com/nikolapejo
    username: npejo
  github:
    url: https://github.com/npejo
    username: npejo
  linkedin:
    url: http://mk.linkedin.com/in/npejo
    username: Nikola Pejoski

slogans:
  - You found my spot on the internet
  - Look around, there might be something useful
  - Sharing thoughts here

# color themes
themes:
  - 'thm-light-blue'
  - 'thm-green-brown'
  - 'thm-pink-brown'
  - 'thm-blue-green'

# animations for displaying background segments
appearAnimations: ['fadeIn', 'zoomIn']

# rules how background segments appearance animation will be delayed
appearDelayStyle: ['linear', 'random']

# default background style
defaults:
  theme: 'thm-blue-green'
  appearAnimation: fadeIn
  delayStyle: random

# Build settings
markdown: kramdown

assets:
  js_compressor:  uglifier
  css_compressor: sass