# Site settings
title: '@nikolapejo'
slogan: sharing thoughts space
email: pejoski@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nikola.pejoski.com" # the base hostname & protocol for your site

social:
  twitter:
    url: https://twitter.com/nikolapejo
    username: npejo
  github:
    url: https://github.com/npejo
    username: npejo
  linkedin:
    url: http://mk.linkedin.com/in/npejo
    username: Nikola Pejoski

slogans:
  - You found my spot on the internet
  - Look around, there might be something useful
  - Sharing thoughts here

defaults:
  appearAnimation: fadeIn
  delayStyle: random

# Build settings
markdown: kramdown

#sass:
#  style: :compressed